{
 "title": "S.M.A.R.T.",
 "description": "Dashboard for disk information based on S.M.A.R.T. data.",
 "tags": [ "prometheus" ],
 "time": { "from": "now-15m", "to": "now" },
 "refresh": "5s",
 "templating": {
  "list": [
   {
    "name": "instance",
    "query": {
     "query": "label_values(smartctl_device_status, instance) "
    }
   },
   {
    "name": "device",
    "query": {
     "query": "label_values(smartctl_device_status, device)"
    }
   }
  ]
 },
 "panels": [
  {
   "title": "General",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 },
   "targets": [
    {}
   ]
  },
  {
   "title": "Devices Monitored",
   "type": "stat",
   "gridPos": { "h": 4, "w": 4, "x": 0, "y": 1 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "sum(smartctl_device_status)", "legendFormat": "__auto" }
   ]
  },
  {
   "title": "Devices",
   "type": "table",
   "gridPos": { "h": 8, "w": 20, "x": 4, "y": 1 },
   "targets": [
    {
     "expr": "smartctl_device_status{ instance=~\"$instance\", device=~\"$device\" }"
    }
   ]
  },
  {
   "title": "Unhealthy Devices",
   "type": "stat",
   "gridPos": { "h": 4, "w": 4, "x": 0, "y": 5 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(smartctl_device_status{instance=~\"$instance\"}) - sum(smartctl_device_status{instance=~\"$instance\"})"
    }
   ]
  },
  {
   "title": "Temperature",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 9 },
   "fieldConfig": { "defaults": { "unit": "celsius" } },
   "targets": [
    {
     "expr": "smartctl_temperature{ instance=~\"$instance\", device=~\"$device\" }",
     "legendFormat": "{{instance}} {{device}}"
    }
   ]
  },
  {
   "title": "Data Written",
   "type": "table",
   "gridPos": { "h": 8, "w": 6, "x": 12, "y": 9 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "expr": "(smartctl_data_units_written{instance=~\"$instance\", device=~\".*nvme.*\", device=~\"$device\"}*512*1024) or (smartctl_data_units_written{instance=~\"$instance\", device=~\"$device\"}*512)"
    }
   ]
  },
  {
   "title": "SSD Percentage used",
   "type": "table",
   "gridPos": { "h": 8, "w": 6, "x": 18, "y": 9 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "targets": [
    {
     "expr": "smartctl_percentage_used{instance=~\"$instance\", device=~\"nvme-.*\", device=~\"$device\"} or 100 - smartctl_wear_leveling_count_value{instance=~\"$instance\", device=~\"$device\"}"
    }
   ]
  },
  {
   "title": "Healthy",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 17 },
   "targets": [
    {}
   ]
  },
  {
   "title": "Power On Hours",
   "type": "bargauge",
   "gridPos": { "h": 4, "w": 12, "x": 0, "y": 18 },
   "fieldConfig": { "defaults": { "unit": "h" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "smartctl_power_on_hours{ device=~\"$device\", instance=~\"$instance\" }",
     "legendFormat": "{{instance}} {{device}}"
    }
   ]
  },
  {
   "title": "Spin Up Time",
   "type": "bargauge",
   "gridPos": { "h": 4, "w": 12, "x": 12, "y": 18 },
   "fieldConfig": { "defaults": { "unit": "ms" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "smartctl_spin_up_time_value{device=~\"$device\", instance=~\"$instance\"}",
     "legendFormat": "{{instance}} {{device}}"
    }
   ]
  },
  {
   "title": "Power Cycle Count",
   "type": "bargauge",
   "gridPos": { "h": 4, "w": 12, "x": 0, "y": 22 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "smartctl_power_cycle_count{device=~\"$device\", instance=~\"$instance\"}",
     "legendFormat": "{{instance}} {{device}}"
    }
   ]
  },
  {
   "title": "Power Off Retract Count",
   "type": "bargauge",
   "gridPos": { "h": 4, "w": 12, "x": 12, "y": 22 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "smartctl_power_off_retract_count{device=~\"$device\", instance=~\"$instance\"}",
     "legendFormat": "{{instance}} {{device}}"
    }
   ]
  },
  {
   "title": "Errors",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 26 },
   "targets": [
    {}
   ]
  },
  {
   "title": "Raw Read Error Rate",
   "type": "bargauge",
   "gridPos": { "h": 4, "w": 12, "x": 0, "y": 27 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "floor((smartctl_raw_read_error_rate{ instance=~\"$instance\", device=~\"$device\" } and smartctl_raw_read_error_rate{device=~\"^ata-ST.*\" } )/4294967296) or smartctl_raw_read_error_rate{ instance=~\"$instance\", device=~\"$device\" }",
     "legendFormat": "{{instance}} {{device}}"
    }
   ]
  },
  {
   "title": "Seek Error Rate",
   "type": "bargauge",
   "gridPos": { "h": 4, "w": 12, "x": 12, "y": 27 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "floor((smartctl_seek_error_rate{ instance=~\"$instance\", device=~\"$device\" } and smartctl_seek_error_rate{device=~\"^ata-ST.*\" } )/4294967296) or smartctl_seek_error_rate{ instance=~\"$instance\", device=~\"$device\" }",
     "legendFormat": "{{instance}} {{device}}"
    }
   ]
  },
  {
   "title": "UDMA CRC Error",
   "type": "bargauge",
   "gridPos": { "h": 4, "w": 12, "x": 0, "y": 31 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "smartctl_udma_crc_error_count{instance=~\"$instance\", device=~\"$device\"}",
     "legendFormat": "{{instance}} {{device}}"
    }
   ]
  },
  {
   "title": "Reallocated Sector Count",
   "type": "bargauge",
   "gridPos": { "h": 4, "w": 12, "x": 12, "y": 31 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "smartctl_reallocated_sector_ct{instance=~\"$instance\", device=~\"$device\"}",
     "legendFormat": "{{instance}} {{device}}"
    }
   ]
  }
 ]
}